#!/usr/bin/env node
// Golden-file tests for the converters.
//
// Why this exists: verify.sh check 12 proves the bash and Node converters agree
// with each other. Agreement is not correctness. A mapping change that is wrong
// in both implementations — read mapped to grep, webfetch granted to a
// read-only role — passes that check forever. These tests compare against a
// reviewed expectation instead.
//
//   node tools/golden.mjs           # compare
//   node tools/golden.mjs --update  # rewrite the goldens after a deliberate change
//
// Exits 0 when every conversion matches, 1 with a diff otherwise.


import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { convert } from '../lib/convert.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GOLDEN = path.join(ROOT, 'tests', 'golden');
const RUNTIMES = ['opencode', 'claude'];
const UPDATE = process.argv.includes('--update');

// A list-form agent, kept as a fixture rather than a real agent. The two OMP
// frontmatter shapes for list-valued keys must convert identically; a parser
// that only reads one of them reports an agent with no tools and renders it as
// "everything denied", which is a silent capability loss.
const FIXTURES = [
  {
    name: 'list-form-agent',
    source: [
      '---',
      'name: list-form-agent',
      'description: Fixture in the block-list tools form OMP bundles use.',
      'model: openai-codex/gpt-6-luna:max',
      'tools:',
      '  - read',
      '  - grep',
      '  - glob',
      '  - lsp',
      '  - web_search',
      '---',
      '',
      'Body text.',
      '',
    ].join('\n'),
  },
];

function agentFiles() {
  const dir = path.join(ROOT, 'agents');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => ({ name: path.basename(f, '.md'), source: readFileSync(path.join(dir, f), 'utf8') }));
}

function* cases() {
  const all = [...agentFiles(), ...FIXTURES];
  for (const item of all) {
    for (const runtime of RUNTIMES) {
      yield { label: `${item.name} -> ${runtime}`, runtime, ...item };
    }
  }
}

function goldenPath(runtime, name) {
  return path.join(GOLDEN, runtime, `${name}.md`);
}

let pass = 0;
const failures = [];

for (const c of cases()) {
  const { text, warnings } = convert(c.source, c.runtime, {});
  const dest = goldenPath(c.runtime, c.name);

  if (UPDATE) {
    mkdirSync(path.dirname(dest), { recursive: true });
    const header = [
      '# GOLDEN FILE - generated by tools/golden.mjs --update. Do not hand-edit.',
      `# source: ${c.name}.md   runtime: ${c.runtime}`,
      '# warnings the conversion emits:',
      ...warnings.map((w) => `#   ${w}`),
      '# /golden-body',
      '',
    ].join('\n');
    writeFileSync(dest, header + text);
    pass += 1;
    continue;
  }

  if (!existsSync(dest)) {
    failures.push({ label: c.label, reason: 'no golden file - run with --update' });
    continue;
  }

  // Compare the body only. The header is regenerated on every run, so asserting
  // on it would turn a reworded warning into a test failure with no
  // behavioural change behind it.
  const raw = readFileSync(dest, 'utf8');
  const marker = '# /golden-body';
  const markerAt = raw.indexOf(marker);
  if (markerAt === -1) {
    failures.push({ label: c.label, reason: 'golden file has no # /golden-body marker' });
    continue;
  }
  const expected = raw.slice(raw.indexOf('\n', markerAt) + 1);
  const actual = text;
  if (expected.trimEnd() !== actual.trimEnd()) {
    failures.push({ label: c.label, expected, actual });
  } else {
    pass += 1;
  }
}

if (UPDATE) {
  process.stdout.write(`  PASS  ${pass} golden file(s) rewritten under tests/golden/\n`);
  process.exit(0);
}

if (failures.length) {
  for (const f of failures) {
    if (f.reason) {
      process.stdout.write(`  FAIL  ${f.label}: ${f.reason}\n`);
      continue;
    }
    process.stdout.write(`  FAIL  ${f.label}\n`);
    const a = f.expected.split('\n');
    const b = f.actual.split('\n');
    let shown = 0;
    for (let i = 0; i < Math.max(a.length, b.length) && shown < 6; i += 1) {
      if (a[i] !== b[i]) {
        process.stdout.write(`        - ${a[i] === undefined ? '(absent)' : a[i]}\n`);
        process.stdout.write(`        + ${b[i] === undefined ? '(absent)' : b[i]}\n`);
        shown += 1;
      }
    }
  }
  process.stdout.write(`  ${pass} matched, ${failures.length} differ. If the change was intended, run: node tools/golden.mjs --update\n`);
  process.exit(1);
}

process.stdout.write(`  PASS  ${pass} conversions match their reviewed goldens\n`);
